//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjCotacaoFreteP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class frete
    {
        public int Id { get; set; }
        public int fkcotacao { get; set; }
        public string codigo_rastreio { get; set; }
        public System.DateTime data_postagem { get; set; }
    
        public virtual cotacao cotacao { get; set; }
    }
}
