//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjCotacaoFreteP2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DadosEntities : DbContext
    {
        public DadosEntities()
            : base("name=DadosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cotacao> cotacao { get; set; }
        public virtual DbSet<embalagem> embalagem { get; set; }
        public virtual DbSet<empresa> empresa { get; set; }
        public virtual DbSet<frete> frete { get; set; }
        public virtual DbSet<pedido> pedido { get; set; }
        public virtual DbSet<transportadora> transportadora { get; set; }
    }
}
