//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjCotacaoFreteP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pedido()
        {
            this.cotacao = new HashSet<cotacao>();
        }
    
        public int Id { get; set; }
        public string nome_cliente { get; set; }
        public string cpf_cnpj { get; set; }
        public string logradouro { get; set; }
        public string cidade { get; set; }
        public string uf { get; set; }
        public string numero { get; set; }
        public string cep { get; set; }
        public string complemento { get; set; }
        public string peso { get; set; }
        public string valor { get; set; }
        public int fkembalagem { get; set; }
        public int fkempresa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cotacao> cotacao { get; set; }
        public virtual embalagem embalagem { get; set; }
        public virtual empresa empresa { get; set; }
    }
}
